name = "мой-воркер"  # Можешь дать любое имя
main = "worker.js"    # Имя файла с кодом (создадим его на следующем шаге)

[assets]
directory = "."       # Папка, откуда брать статику. "." означает корень репозитория
binding = "ASSETS"    # Обязательное имя привязки для доступа к статике из кода
run_worker_first = true # Важно! Сначала выполнять код Worker'а, потом отдавать статику
